<a href="https://colab.research.google.com/github/aviralshukla2007-hue/project_calc/blob/main/Arrays_using_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# To create 1D array using NumPy

import numpy as np
a = [1,2,3,4]
arr = np.array(a)
print("List in Python:",a)
print("Array in NumPy:",arr)

List in Python: [1, 2, 3, 4]
Array in NumPy: [1 2 3 4]


In [ ]:
# To check the datatype of the 1D array
print(type(a))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
#To create a multi-dimension array using NumPy

import numpy as np

list_1 = [1,2,3,4]
list_2 = [5,6,7,8]
list_3 = [7,8,9,10]

arr = np.array([list_1,
                list_2,
                list_3])

print("Numpy multi-dimensional array in python\n:",arr)

Numpy multi-dimensional array in python
: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 7  8  9 10]]


In [ ]:
import numpy as np

sample_array = np.array([1,2,3,4,5,6,7,8,9,10])
sample_array_1 = np.array([1.6, 2.6, 3.6, 4.6, 5.6])

print("Data type of the first array:",sample_array.dtype)
print("Data type of the second array:",sample_array_1.dtype)

Data type of the first array: int64
Data type of the second array: float64


In [ ]:
# Creation of Array using numpy.array()

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])

print("Array:",arr)

Array: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
import numpy as np
sample_array = np.array([[0, 4, 2],
                       [3, 4, 5],
                       [23, 4, 5],
                       [2, 34, 5],
                       [5, 6, 7]])

print("shape of the array :",
      sample_array.shape)

shape of the array : (5, 3)


In [ ]:
import numpy as np
var = "Hello There!"
arr=np.fromiter(var, dtype = 'U2')
print("fromiter() arr:", arr)

fromiter() arr: ['H' 'e' 'l' 'l' 'o' ' ' 'T' 'h' 'e' 'r' 'e' '!']


In [7]:
import numpy as np
x = [1,2,3,4]
y = [5,6,7,8]
z = [9,10,11,12]

arr = np.array([x,
                y,
                z])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
import pandas as pd
import numpy as np
s = pd.Series([1,3,5,np.nan,6,8])
s

,0
0,1.0
1,3.0
2,5.0
3,NaN
4,6.0
5,8.0


In [ ]:
import pandas as pd
import numpy as np
dates = pd.date_range("20260617")